# api/core_apps/common/constants/files.py
FILE_PATH_MAX_LENGTH = 512
FILE_ORIGINAL_NAME_MAX_LENGTH = 256
FILE_MIME_TYPE_MAX_LENGTH = 128
FILE_EXTENSION_MAX_LENGTH = 16
FILE_CHECKSUM_SHA256_LENGTH = 64
